version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: file:./dev.db
      AUTH0_CLIENT_ID: g75qjtaovv598NsXyrmCSVw9wXQCzJiH
      AUTH0_DOMAIN: dev-cc8jlpsr.eu.auth0.com
      AUTH0_CLIENT_SECRET: 6NWBQjFFq6cR0pw0GGlk6LKtbNevXds--4CVG-r1zE2y9UOpQKCxF_ZRD7hTOAWW
      AUTH0_CALLBACK_URL: http://localhost:3333/api/auth/auth0/callback
      SESSION_SECRET: 730e89d233bc73a56eeb5ac180fad100edbd04cf28de04147cdb9ce77b3ce64a
